module.exports = [
    {
        id: 1,
        name: "Battle of the Chart Toppers",
        rapper1_id: 1,
        rapper2_id: 2,
        rapper1_wins: 34,
        rapper2_wins: 17,
        total_battles: 51,
    },
    {
        id: 2,
        name: "Battle of the Poets",
        rapper1_id: 5,
        rapper2_id: 10,
        rapper1_wins: 21,
        rapper2_wins: 13,
        total_battles: 34,
    },
    {
        id: 3,
        name: "Battle of the BARS",
        rapper1_id: 12,
        rapper2_id: 15,
        rapper1_wins: 24,
        rapper2_wins: 19,
        total_battles: 43,
    },
    {
        id: 4,
        name: "Battle of the Brains",
        rapper1_id: 7,
        rapper2_id: 11,
        rapper1_wins: 19,
        rapper2_wins: 27,
        total_battles: 46,
    },
    {
        id: 5,
        name: "Battle of the Rhymers",
        rapper1_id: 4,
        rapper2_id: 19,
        rapper1_wins: 25,
        rapper2_wins: 19,
        total_battles: 44,
    },
];
