module.exports = [
    {
        id: 1,
        name: "Battle of the Chart Toppers",
        rapper1_id: 1,
        rapper2_id: 2,
        rapper1_name: "Jay-Z",
        rapper2_name: "Drake",
        rapper1_wins: 22,
        rapper2_wins: 12,
        total_battles: 40,
    },
    {
        id: 2,
        name: "Battle of the Poets",
        rapper1_id: 5,
        rapper2_id: 10,
        rapper1_name: "Andre 3000",
        rapper2_name: "Lauryn Hill",
        rapper1_wins: 20,
        rapper2_wins: 11,
        total_battles: 31,
    },
    {
        id: 3,
        name: "Battle of the BARS",
        rapper1_id: 12,
        rapper2_id: 15,
        rapper1_name: "Lil Wayne",
        rapper2_name: "Jadakiss",
        rapper1_wins: 12,
        rapper2_wins: 9,
        total_battles: 21,
    },
    {
        id: 4,
        name: "Battle of the Brains",
        rapper1_id: 7,
        rapper2_id: 11,
        rapper1_name: "Black Thought",
        rapper2_name: "Lupe Fiasco",
        rapper1_wins: 13,
        rapper2_wins: 19,
        total_battles: 32,
    },
    {
        id: 5,
        name: "Battle of the Rhymers",
        rapper1_id: 4,
        rapper2_id: 19,
        rapper1_name: "Eminem",
        rapper2_name: "Big Pun",
        rapper1_wins: 15,
        rapper2_wins: 11,
        total_battles: 26,
    },
];
