module.exports = [
    {
        id: 1,
        name: "Jay-Z",
        wins: 66,
        losses: 23,
    },
    {
        id: 2,
        name: "Drake",
        wins: 42,
        losses: 17,
    },
    {
        id: 3,
        name: "The Notorious B.I.G",
        wins: 29,
        losses: 6,
    },
    {
        id: 4,
        name: "Eminem",
        wins: 43,
        losses: 19,
    },
    {
        id: 5,
        name: "Andre 3000",
        wins: 39,
        losses: 7,
    },
    {
        id: 6,
        name: "Big Boi",
        wins: 17,
        losses: 5,
    },
    {
        id: 7,
        name: "Black Thought",
        wins: 29,
        losses: 8,
    },
    {
        id: 8,
        name: "Ye",
        wins: 44,
        losses: 35,
    },
    {
        id: 9,
        name: "Snoop Dogg",
        wins: 32,
        losses: 14,
    },
    {
        id: 10,
        name: "Lauryn Hill",
        wins: 33,
        losses: 3,
    },
    {
        id: 11,
        name: "Lupe Fiasco",
        wins: 37,
        losses: 11,
    },
    {
        id: 12,
        name: "Lil Wayne",
        wins: 36,
        losses: 13,
    },
    {
        id: 13,
        name: "Kendrick Lamar",
        wins: 45,
        losses: 14,
    },
    {
        id: 14,
        name: "J Cole",
        wins: 32,
        losses: 12,
    },
    {
        id: 15,
        name: "Jadakiss",
        wins: 28,
        losses: 18,
    },
    {
        id: 16,
        name: "Tupac",
        wins: 44,
        losses: 16,
    },
    {
        id: 17,
        name: "Chance The Rapper",
        wins: 28,
        losses: 19,
    },
    {
        id: 18,
        name: "Talib Kweli",
        wins: 26,
        losses: 6,
    },
    {
        id: 19,
        name: "Big Pun",
        wins: 42,
        losses: 21,
    },
    {
        id: 20,
        name: "Killer Mike",
        wins: 33,
        losses: 15,
    },
];
