module.exports = [
    {
        id: 1,
        name: "Jay-Z",
        wins: 34,
        losses: 12,
    },
    {
        id: 2,
        name: "Drake",
        wins: 45,
        losses: 15,
    },
    {
        id: 3,
        name: "The Notorious B.I.G",
        wins: 56,
        losses: 23,
    },
    {
        id: 4,
        name: "Eminem",
        wins: 67,
        losses: 34,
    },
    {
        id: 5,
        name: "Andre 3000",
        wins: 78,
        losses: 45,
    },
    {
        id: 6,
        name: "Big Boi",
        wins: 89,
        losses: 56,
    },
    {
        id: 7,
        name: "Black Thought",
        wins: 90,
        losses: 67,
    },
    {
        id: 8,
        name: "Ye",
        wins: 12,
        losses: 78,
    },
    {
        id: 9,
        name: "Snoop Dogg",
        wins: 23,
        losses: 89,
    },
    {
        id: 10,
        name: "Lauryn Hill",
        wins: 34,
        losses: 90,
    },
    {
        id: 11,
        name: "Lupe Fiasco",
        wins: 45,
        losses: 12,
    },
    {
        id: 12,
        name: "Lil Wayne",
        wins: 56,
        losses: 23,
    },
    {
        id: 13,
        name: "Kendrick Lamar",
        wins: 67,
        losses: 34,
    },
    {
        id: 14,
        name: "J Cole",
        wins: 78,
        losses: 45,
    },
    {
        id: 15,
        name: "Jadakiss",
        wins: 89,
        losses: 56,
    },
    {
        id: 16,
        name: "Tupac",
        wins: 90,
        losses: 67,
    },
    {
        id: 17,
        name: "Chance The Rapper",
        wins: 12,
        losses: 78,
    },
    {
        id: 18,
        name: "Talib Kweli",
        wins: 23,
        losses: 89,
    },
    {
        id: 19,
        name: "Big Pun",
        wins: 34,
        losses: 90,
    },
    {
        id: 20,
        name: "Killer Mike",
        wins: 45,
        losses: 12,
    },
];
