module.exports = [
    {
        id: 1,
        name: "Jay-Z",
        wins: 22,
        losses: 4,
    },
    {
        id: 2,
        name: "Drake",
        wins: 17,
        losses: 7,
    },
    {
        id: 3,
        name: "The Notorious B.I.G",
        wins: 29,
        losses: 6,
    },
    {
        id: 4,
        name: "Eminem",
        wins: 21,
        losses: 3,
    },
    {
        id: 5,
        name: "Andre 3000",
        wins: 29,
        losses: 0,
    },
    {
        id: 6,
        name: "Big Boi",
        wins: 17,
        losses: 5,
    },
    {
        id: 7,
        name: "Black Thought",
        wins: 20,
        losses: 4,
    },
    {
        id: 8,
        name: "Ye",
        wins: 14,
        losses: 5,
    },
    {
        id: 9,
        name: "Snoop Dogg",
        wins: 22,
        losses: 4,
    },
    {
        id: 10,
        name: "Lauryn Hill",
        wins: 19,
        losses: 1,
    },
    {
        id: 11,
        name: "Lupe Fiasco",
        wins: 17,
        losses: 0,
    },
    {
        id: 12,
        name: "Lil Wayne",
        wins: 26,
        losses: 8,
    },
    {
        id: 13,
        name: "Kendrick Lamar",
        wins: 25,
        losses: 4,
    },
    {
        id: 14,
        name: "J Cole",
        wins: 22,
        losses: 2,
    },
    {
        id: 15,
        name: "Jadakiss",
        wins: 18,
        losses: 8,
    },
    {
        id: 16,
        name: "Tupac",
        wins: 21,
        losses: 6,
    },
    {
        id: 17,
        name: "Chance The Rapper",
        wins: 18,
        losses: 9,
    },
    {
        id: 18,
        name: "Talib Kweli",
        wins: 16,
        losses: 6,
    },
    {
        id: 19,
        name: "Big Pun",
        wins: 12,
        losses: 1,
    },
    {
        id: 20,
        name: "Killer Mike",
        wins: 13,
        losses: 5,
    },
];
